name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Target environment (dev, test, preprod, prod)"
      acr_name:
        required: false
        type: string
        default: "default-acr-name"
        description: "Azure Container Registry name"
      helm_chart_path:
        required: true
        type: string
        description: "Path to the Helm chart values file"
      version_tag:
        required: true
        type: string
        description: "Docker image version tag"
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ inputs.acr_name }}.azurecr.io
          username: ${{ secrets.AZURE_CREDENTIALS.clientId }}
          password: ${{ secrets.AZURE_CREDENTIALS.clientSecret }}

      - name: Build Docker image
        run: |
          docker build -t ${{ inputs.acr_name }}.azurecr.io/my-app:${{ inputs.version_tag }} .

      - name: Push Docker image to ACR
        run: |
          docker push ${{ inputs.acr_name }}.azurecr.io/my-app:${{ inputs.version_tag }}
