name: Trunk-Based CI/CD Pipeline

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Target environment (dev, test, preprod, prod)"
      acr_name:
        required: false
        type: string
        default: "default-acr-name" # Provide your default ACR name here
        description: "Azure Container Registry name"
      helm_chart_path:
        required: true
        type: string
        description: "Path to the Helm chart values file"
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  versioning:
    uses: .github/workflows/semantic-version-tagging.yml@main
    outputs:
      next_tag: ${{ steps.versioning.outputs.next_tag }}

  build-and-push-image:
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ inputs.acr_name }}.azurecr.io
          username: ${{ secrets.AZURE_CREDENTIALS.clientId }}
          password: ${{ secrets.AZURE_CREDENTIALS.clientSecret }}

      - name: Build Docker image
        run: |
          docker build -t ${{ inputs.acr_name }}.azurecr.io/my-app:${{ needs.versioning.outputs.next_tag }} .
      
      - name: Push Docker image to ACR
        run: |
          docker push ${{ inputs.acr_name }}.azurecr.io/my-app:${{ needs.versioning.outputs.next_tag }}

          