name: Trunk-Based CI/CD Pipeline

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Target environment (dev, test, preprod, prod)"
      acr_name:
        required: false
        type: string
        default: "default-acr-name"
        description: "Azure Container Registry name"
      helm_chart_path:
        required: true
        type: string
        description: "Path to the Helm chart values file"
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  versioning:
    uses: .github/workflows/semantic-version-tagging.yml@main
    outputs:
      next_tag: ${{ steps.versioning.outputs.next_tag }}

  build-and-push-image:
    needs: versioning
    uses: .github/workflows/build-and-push.yml@main
    with:
      environment: ${{ inputs.environment }}
      acr_name: ${{ inputs.acr_name }}
      helm_chart_path: ${{ inputs.helm_chart_path }}
      version_tag: ${{ needs.versioning.outputs.next_tag }}
